server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/portfolio_alerts
spring.datasource.username=root
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


jwt.secret=VGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBqd3Q=
jwt.expiration=86400000


spring.data.redis.host=localhost
spring.data.redis.port=6379


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest



spring.kafka.bootstrap-servers=localhost:9092


logging.level.org.springframework.security=INFO